### ISSUE TITLE
Move remaining "common" utils into core-utils

### ISSUE THREAD

**Issue by smartcontracts** [ethereum-optimism/data-transport-layer#45]
Via @tynes. Agree here and we should try to move anything that looks like a useful utility into `core-utils`.

---

These should exist in `core-utils` ideally

_Originally posted by @tynes in https://github.com/ethereum-optimism/data-transport-layer/pull/40#discussion_r578775812_

**Comment by platocrat** [comment]
Made a PR here: https://github.com/ethereum-optimism/core-utils/pull/8

I migrated the utils from `data-transport-layer/src/common/common.ts` to [`core-utils/src/common/common.ts`](https://github.com/ethereum-optimism/core-utils/pull/8/files) without touching anything in `data-transport-layer`. 

Did you want to also refactor dependent files in `data-transport-layer` that import `common.ts`, or is this sufficient?

**Comment by smartcontracts** [comment]
Ok this can be closed.
